[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[font]
size = 20

[font.bold]
family = "Source Code Pro"
style = "Regular"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"

[window.dimensions]
columns = 125
lines = 35

[window.padding]
x = 5
y = 5

[window.position]
x = 100
y = 250
