cask 'betterdisplay'
cask 'bitwarden'
cask 'brave-browser'
cask 'discord'
cask 'disk-inventory-x'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'geekbench'
cask 'iina'
cask 'intellij-idea'
cask 'microsoft-edge'
cask 'microsoft-remote-desktop'
cask 'monitorcontrol'
cask 'protonvpn'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'vlc'
cask 'vmware-fusion'
cask 'zoom'

mas 'mindnode', id: 1289197285
